services:
  server:
  build:
    context: ./server
    dockerfile: Dockerfile.server
  ports:
    - "3000:5000"
  volumes:
    - ./server:./app
    - /app/node_modules
  environment:
    - DATABASE_URL=postgres://postgres:postgres@db:5432/app_db
    - HOST=db
    - USER=postgres
    - PASSWORD=postgres
    - DB=app_db
    - DB_PORT=5432
    - SERVER_PORT=5000
  depends_on:
    - db

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.client
    ports:
      - "5173:5173"
    volumes:
      - ./client:./app
      - /app/node_modules  
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - server

  db:
    image: postgres:16
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_db=app_db
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
